name: Dependabot

on:
    schedule:
        - cron: "30 11 * * 5"

jobs:
    build:
        runs-on : ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Update depedencies
          run: |
            cargo update
            gh pr create -t "Update depedencies" -b "Automatic Pull Request" -l "bot/update" || gh pr edit main -l "bot/update"