name: CI

on:
  release:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run the makefile
        run: make build


name: DevMode

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on : ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build on check mode and launch the tests
        run: make tests


